#!/bin/sh
set -e

if [ "$1" = configure ]; then
  if ! test -d /var/run/screen; then
    install -g utmp -m 0775 -d /var/run/screen
    [ `stat -c%a /usr/bin/screen` -lt 4000 ] || chmod 0755 /var/run/screen
  fi
  add-shell /usr/bin/screen || true
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/screen-cleanup" ]; then
	update-rc.d screen-cleanup start 70 S . >/dev/null || exit $?
fi
# End automatically added section

