#! /bin/sh

# sysklogd	Cron script to rotate system log files weekly.
#
#		If you want to rotate logfiles daily, edit
#		this script and /etc/cron.daily/sysklogd to get
#		the logfiles in sync (they must not occur in both
#		files).
#
#		This is a configration file.  You are invited to edit
#		it and maintain it on your own.  You'll have to do
#		that if you don't like the default policy
#		wrt. rotating logfiles (i.e. with large logfiles
#		weekly and daily rotation may interfere).  If you edit
#		this file and don't let dpkg upgrade it, you have full
#		control over it.  Please read the manpage to
#		syslogd-listfiles.
#
#		Written by Ian A. Murdock <imurdock@debian.org>.
#		$Id: cron.weekly,v 1.11 2007-05-28 16:33:34 joey Exp $

test -x /usr/sbin/syslogd-listfiles || exit 0
test -x /sbin/syslogd || exit 0
test -f /usr/share/sysklogd/dummy || exit 0

set -e

USER=$(ps -C syslogd -o user= | head -n 1)
[ -z "${USER}" ] && USER="root" || true

cd /var/log

logs=$(syslogd-listfiles --weekly)

test -n "$logs" || exit 0

for LOG in $logs
do
   if [ -s $LOG ]; then
      savelog -g adm -m 640 -u ${USER} -c 4 $LOG >/dev/null
   fi
done

# Restart syslogd
#
/etc/init.d/sysklogd reload-or-restart > /dev/null
